inline NetUtils.bindToLocalAddress, introduced only in 3.1.1
NoSuchMethodError: org.apache.hadoop.net.NetUtils.bindToLocalAddress(Ljava/net/InetAddress;Z)Ljava/net/InetAddress