copy GlobPattern from Hadoop due to mismatch of shaded/non-shaded signature:
NoSuchMethodError: org.apache.hadoop.fs.GlobPattern.compile(Ljava/lang/String;)Lorg/apache/ozone/shaded/com/google/re2j/Pattern